version: "3.8"

services:
  app:
    image: php:8.2-apache
    container_name: todolist-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    working_dir: /var/www/html
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: todolist-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todolist
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todolist-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8081:80"

volumes:
  db_data:
